### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by dhthwy** [dhthwy/SDL-Console-Plus#1]
- [x]  Don't render lines outside the viewport (performance, memory)
- [ ]  Implement ANSI/vt100 terminal emulation
- [ ]  Make it more configurable
- [ ]  Implement vertical scrollbar
- [x]  Implement clipboard operations
- [x]  Enforce a minimum window size

**Comment by dhthwy** [comment]
- [ ] Needs storage location for chars
- [ ] Needs a construct to notify when char is stored
